const mysql=require('../../src/node_modules/mysql2/promise');
const request=require('../../src/node_modules/supertest');
const fs=require('node:fs'),path=require('node:path');
const enabled=process.env.CR001_TEST_DB_PORT&&process.env.CR001_TEST_DB_NAME;
(enabled?describe:describe.skip)('CR-001 isolated MySQL profile/session/navigation',()=>{
 let admin,pool,app,sessions,ids={},hash;
 const saved={...process.env},database=process.env.CR001_TEST_DB_NAME;
 const password='StrongPassword@123';
 beforeAll(async()=>{
  if(!/^tms_cr001_[a-z0-9_]+_test$/.test(database))throw new Error('Dedicated CR-001 test database required.');
  admin=await mysql.createConnection({host:process.env.CR001_TEST_DB_HOST||'127.0.0.1',port:Number(process.env.CR001_TEST_DB_PORT),user:process.env.CR001_TEST_DB_USER||'root',password:process.env.CR001_TEST_DB_PASSWORD,multipleStatements:true,timezone:'Z'});
  await admin.query(`CREATE DATABASE \`${database}\``);await admin.query(`USE \`${database}\``);
  for(const file of ['v1.0_participant-account-schema.sql','v1.1_participant-authentication-schema.sql'])await admin.query(fs.readFileSync(path.join(__dirname,'../../db/migrations',file),'utf8'));
  const [actors]=await admin.query("SELECT account_identifier FROM users WHERE authentication_method='SYSTEM'");
  Object.assign(process.env,{DB_HOST:process.env.CR001_TEST_DB_HOST||'127.0.0.1',DB_PORT:process.env.CR001_TEST_DB_PORT,DB_USER:process.env.CR001_TEST_DB_USER||'root',DB_PASSWORD:process.env.CR001_TEST_DB_PASSWORD,DB_NAME:database,SESSION_SECRET:'cr001-isolated-session-secret-'.repeat(3),SESSION_COOKIE_SECURE:'false',SYSTEM_AUDIT_ACTOR_ACCOUNT_IDENTIFIER:actors[0].account_identifier});
  hash=await require('../../src/auth/password-hasher').hashPassword(password);
  for(const role of ['PARTICIPANT','TRAINER','TRAINING_ADMINISTRATOR','SYSTEM_ADMINISTRATOR']){
   const [result]=await admin.execute(`INSERT INTO users (account_identifier,username,name,email,password_hash,role_id,role_name,permissions,access_scope,permitted_responsibilities,account_status,role_assigned_at,authentication_method,created_at,updated_at)
    VALUES (?,?,?,?,?,?,?,'[]','[]','[]','ACTIVE',UTC_TIMESTAMP(),'PASSWORD',UTC_TIMESTAMP(),UTC_TIMESTAMP())`,['A-'+role,role,'Own '+role,role.toLowerCase()+'@example.test',hash,role,role]);ids[role]=String(result.insertId);
  }
  await admin.execute("INSERT INTO participants(user_id,nric_passport_no,name,mobile_no,created_at,updated_at) VALUES (?,'PRIVATE-NRIC-1234','Own Participant','0123456',UTC_TIMESTAMP(),UTC_TIMESTAMP())",[ids.PARTICIPANT]);
  pool=require('../../src/config/database');app=require('../../src/app');sessions=require('../../src/bindings/participant-authentication.bindings').sessions;
 },30000);
 beforeEach(async()=>{await admin.query('DELETE FROM sessions; DELETE FROM audit_records; DELETE FROM authentication_failures;');await admin.execute('UPDATE users SET email=?,account_status=\'ACTIVE\' WHERE user_id=?',['participant@example.test',ids.PARTICIPANT]);await admin.execute('UPDATE participants SET mobile_no=? WHERE user_id=?',['0123456',ids.PARTICIPANT]);});
 afterAll(async()=>{if(pool)await pool.end();if(admin){await admin.query(`DROP DATABASE \`${database}\``);await admin.end();}for(const key of Object.keys(process.env))if(!(key in saved))delete process.env[key];Object.assign(process.env,saved);});
 async function session(role){const principal={userId:ids[role],role};if(role==='PARTICIPANT'){const [rows]=await admin.execute('SELECT participant_id FROM participants WHERE user_id=?',[ids[role]]);principal.participantId=String(rows[0].participant_id);}
  const plan=await sessions.prepare({connection:pool,now:new Date(),preparedSessionIds:[]},{},principal);const [rows]=await admin.execute('SELECT session_data FROM sessions WHERE session_id=?',[plan.cookiePlan.sessionId]);return {cookie:'tms.sid='+plan.cookiePlan.value,token:JSON.parse(rows[0].session_data).csrfToken,id:plan.cookiePlan.sessionId};}
 test.each([['PARTICIPANT','participants'],['TRAINER','staff'],['TRAINING_ADMINISTRATOR','staff'],['SYSTEM_ADMINISTRATOR','system-admin']])('TC-CR-002 existing API authenticates %s with canonical role',async(role,endpoint)=>{
  const result=await request(app).post('/api/v1/auth/'+endpoint+'/login').send({email:role.toLowerCase()+'@example.test',password}).expect(200);expect(result.body.role).toBe(role);expect(result.headers['set-cookie'][0]).toContain('tms.sid=');
 },30000);
 test.each(['PARTICIPANT','TRAINER','TRAINING_ADMINISTRATOR','SYSTEM_ADMINISTRATOR'])('TC-CR-008 own profile for %s',async role=>{const auth=await session(role);const result=await request(app).get('/api/v1/profile').set('Cookie',auth.cookie).expect(200);expect(String(result.body.userId)).toBe(ids[role]);expect(result.body.editableFields).toEqual(role==='PARTICIPANT'?['email','mobileNo']:['email']);expect(JSON.stringify(result.body)).not.toMatch(/PRIVATE-NRIC|password|permissions|session|csrf/);});
 test('TC-CR-003/004/005 real session gates protect dashboard and existing function URLs',async()=>{const participant=await session('PARTICIPANT'),trainer=await session('TRAINER');await request(app).get('/participant/dashboard').set('Cookie',participant.cookie).expect(200);await request(app).get('/staff/dashboard').set('Cookie',participant.cookie).expect(403);await request(app).get('/system-admin/dashboard').set('Cookie',trainer.cookie).expect(403);await request(app).get('/admin/users').set('Cookie',trainer.cookie).expect(403);});
 test('TC-CR-006 logout removes signed session and old cookie is unusable',async()=>{const auth=await session('PARTICIPANT');const result=await request(app).post('/api/v1/auth/logout').set('Cookie',auth.cookie).set('X-CSRF-Token',auth.token).expect(204);expect(result.headers['set-cookie'][0]).toContain('Expires=Thu, 01 Jan 1970');const [rows]=await admin.execute('SELECT * FROM sessions WHERE session_id=?',[auth.id]);expect(rows).toHaveLength(0);await request(app).get('/profile').set('Cookie',auth.cookie).expect(401);});
 test('TC-CR-007 expired cookie denies APIs and browser page shows blocking recovery without profile data',async()=>{const auth=await session('PARTICIPANT');await admin.execute('UPDATE sessions SET expires_at=UTC_TIMESTAMP()-INTERVAL 1 SECOND WHERE session_id=?',[auth.id]);await request(app).get('/api/v1/profile').set('Cookie',auth.cookie).expect(401);const result=await request(app).get('/profile').set('Cookie',auth.cookie).set('Accept','text/html').expect(401);expect(result.text).toContain('data-session-expired');expect(result.text).toContain('expiredSessionLogout');expect(result.text).not.toContain('participant@example.test');});
 test('TC-CR-009/010 own contact fields persist, protected fields fail, and updates are audited',async()=>{const auth=await session('PARTICIPANT');await request(app).put('/api/v1/profile').set('Cookie',auth.cookie).set('X-CSRF-Token',auth.token).send({name:'Forged'}).expect(400);await request(app).put('/api/v1/profile').set('Cookie',auth.cookie).set('X-CSRF-Token',auth.token).send({email:'NEW@EXAMPLE.TEST',mobileNo:'0199999'}).expect(200);const [rows]=await admin.execute('SELECT u.email,p.mobile_no,p.name,p.nric_passport_no FROM users u JOIN participants p ON p.user_id=u.user_id WHERE u.user_id=?',[ids.PARTICIPANT]);expect(rows[0]).toMatchObject({email:'new@example.test',mobile_no:'0199999',name:'Own Participant',nric_passport_no:'PRIVATE-NRIC-1234'});const [events]=await admin.query("SELECT * FROM audit_records WHERE action='ACCOUNT_UPDATED'");expect(events).toHaveLength(1);expect(JSON.stringify(events)).not.toContain('PRIVATE-NRIC');});
 test('profile uniqueness failure changes neither email nor mobile',async()=>{const auth=await session('PARTICIPANT');await request(app).put('/api/v1/profile').set('Cookie',auth.cookie).set('X-CSRF-Token',auth.token).send({email:'trainer@example.test',mobileNo:'0199999'}).expect(409);const [rows]=await admin.execute('SELECT u.email,p.mobile_no FROM users u JOIN participants p ON p.user_id=u.user_id WHERE u.user_id=?',[ids.PARTICIPANT]);expect(rows[0]).toEqual({email:'participant@example.test',mobile_no:'0123456'});});
 test('mandatory profile audit failure rolls back contact changes',async()=>{const auth=await session('PARTICIPANT');await admin.query("CREATE TRIGGER cr001_profile_audit_failure BEFORE INSERT ON audit_records FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Injected audit failure'");try{await request(app).put('/api/v1/profile').set('Cookie',auth.cookie).set('X-CSRF-Token',auth.token).send({email:'new@example.test',mobileNo:'0199999'}).expect(500);const [rows]=await admin.execute('SELECT u.email,p.mobile_no FROM users u JOIN participants p ON p.user_id=u.user_id WHERE u.user_id=?',[ids.PARTICIPANT]);expect(rows[0]).toEqual({email:'participant@example.test',mobile_no:'0123456'});}finally{await admin.query('DROP TRIGGER cr001_profile_audit_failure');}});
 test('CSRF rejection is audited and leaves session/profile unchanged',async()=>{const auth=await session('PARTICIPANT');await request(app).put('/api/v1/profile').set('Cookie',auth.cookie).send({email:'new@example.test'}).expect(403);await request(app).post('/api/v1/auth/logout').set('Cookie',auth.cookie).expect(403);const [rows]=await admin.query("SELECT * FROM audit_records WHERE action='CSRF_REJECTED'");expect(rows).toHaveLength(2);await request(app).get('/api/v1/profile').set('Cookie',auth.cookie).expect(200);});
});
