// Initial UI conventions approved for WF-001. Bootstrap is centralized here
// so a later asset pipeline can replace the CDN without changing the feature.
module.exports = Object.freeze({
  homeUrl: '/',
  profileUrl: '/profile',
  commonLoginJsUrl: '/js/login.js',
  bootstrapJsIntegrity: 'sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI',
  bootstrapJsUrl: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js',
  participantRegistrationUrl: '/register',
  participantLoginUrl: '/login',
  bootstrapCssUrl: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css',
  bootstrapCssIntegrity: 'sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB',
  appCssUrl: '/css/app.css',
  participantRegisterJsUrl: '/js/participant-register.js',
  programListUrl: '/programs',
  systemAdministratorBootstrapUrl: '/admin/bootstrap',
  administrativeLoginUrl: '/admin/login',
  systemAdministratorBootstrapJsUrl: '/js/system-administrator-bootstrap.js',
  adminLandingUrl: '/admin/users',
  administrativeUserCreateJsUrl: '/js/administrative-user-create.js',
  staffLoginUrl: '/staff/login',
  trainingAdministratorLandingUrl: '/admin/programs',
  trainerLandingUrl: '/trainer/programs',
  programListJsUrl: '/js/program-list.js',
  programDetailsBaseUrl: '/programs',
  programDetailJsUrl: '/js/program-detail.js',
  programRegistrationUrlTemplate: '/programs/:programId/register',
  participantRegistrationJsUrl: '/js/participant-registration.js',
  myRegistrationsUrl: '/registrations',
  myRegistrationsJsUrl: '/js/my-registrations.js',
  accountFormsJsUrl: '/js/account-forms.js',
  businessTimeJsUrl: '/js/business-time.js',
  categoryManagementUrl: '/admin/categories',
  programManagementJsUrl: '/js/program-management.js',
  registrationManagementUrl: '/admin/registrations',
  registrationManagementJsUrl: '/js/registration-management.js',
  attendanceManagementJsUrl: '/js/attendance-management.js',
  certificateManagementUrl: '/admin/certificates',
  certificateManagementJsUrl: '/js/certificate-management.js',
  reportsUrl: '/admin/reports',
  reportsJsUrl: '/js/reports.js'
});
