const express = require('express');
const path = require('path');
const publicUiRoutes = require('./routes/public-ui.routes');
const participantAuthRoutes = require('./routes/participant-auth.routes');
const correlationIdMiddleware = require('./middleware/correlation-id.middleware');
const errorHandler = require('./middleware/error-handler.middleware');
const { wrapJsonParser } = require('./middleware/implementation-errors');
const { errors } = require('./auth/authentication-errors');
const { assemble } = require('./participant-authentication.composition');
const { bindings } = require('./participant-authentication.bindings');

const app = express();
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(correlationIdMiddleware);
app.use(wrapJsonParser(express.json({ type: 'application/json', limit: '100kb' }), errors));
app.use(express.static(path.join(__dirname, 'public')));
app.use(publicUiRoutes);
app.use('/api/v1/auth', participantAuthRoutes);
app.use('/api/v1', assemble(bindings));
app.use('/api/v1', require('./system-administrator-bootstrap.composition').assemble(require('./system-administrator-bootstrap.bindings')));
app.use(errorHandler);
module.exports = app;
