const express = require('express');
const path = require('path');
const publicUiRoutes = require('./routes/public-ui.routes');
const participantAuthRoutes = require('./routes/participant-auth.routes');
const correlationIdMiddleware = require('./middleware/correlation-id.middleware');
const errorHandler = require('./middleware/error-handler.middleware');
const { wrapJsonParser } = require('./middleware/implementation-errors');
const { errors } = require('./auth/authentication-errors');
const { assemble } = require('./participant-authentication.composition');
const { bindings } = require('./participant-authentication.bindings');

const app = express();
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(correlationIdMiddleware);
app.use(wrapJsonParser(express.json({ type: 'application/json', limit: '100kb' }), errors));
app.use(express.static(path.join(__dirname, 'public')));
app.use(publicUiRoutes);
app.use('/api/v1/auth', participantAuthRoutes);
app.use('/api/v1', assemble(bindings));
app.use('/api/v1', require('./system-administrator-authentication.composition').assemble(bindings));
app.use('/api/v1', require('./staff-authentication.composition').assemble(bindings));
app.use('/api/v1', require('./system-administrator-bootstrap.composition').assemble(require('./system-administrator-bootstrap.bindings')));
const administrativeUsers = require('./administrative-user-creation.bindings');
app.use('/api/v1', require('./administrative-user-creation.composition').assemble(administrativeUsers));
app.use(require('./routes/administrative-user-creation.routes').makePageRouter(administrativeUsers));
const catalogue = require('./program-catalogue.bindings');
app.use('/api/v1', require('./program-catalogue.composition').assemble(catalogue));
app.use(require('./routes/program-catalogue-ui.routes').makePageRouter(catalogue));
app.use('/api/v1', require('./program-details.composition').assemble(require('./program-details.bindings')));
app.use(require('./routes/program-details-ui.routes').makePageRouter());
const registrations = require('./participant-program-registration.bindings');
app.use('/api/v1', require('./participant-program-registration.composition').assemble(registrations));
app.use(require('./routes/participant-registration-ui.routes').makePageRouter(registrations, require('./program-details.bindings').programs));
const cancellation = require('./participant-registration-cancellation.bindings');
app.use('/api/v1', require('./participant-registration-cancellation.composition').assemble(cancellation));
app.use(require('./routes/my-registrations-ui.routes').makePageRouter(cancellation));
const management=require('./training-program-category-management.bindings');
app.use('/api/v1',require('./training-program-category-management.composition').assemble(management));
app.use(require('./routes/training-management-ui.routes').makePageRouter(management));
const registrationManagement = require('./registration-management-view.bindings');
app.use('/api/v1', require('./registration-management-view.composition').assemble(registrationManagement));
app.use(require('./routes/registration-management-ui.routes').makePageRouter(registrationManagement));
app.use(errorHandler);
module.exports = app;
