const express = require('express');
const path = require('path');
const publicUiRoutes = require('./routes/public-ui.routes');
const participantAuthRoutes = require('./routes/participant-auth.routes');
const correlationIdMiddleware = require('./middleware/correlation-id.middleware');
const errorHandler = require('./middleware/error-handler.middleware');
const { wrapJsonParser } = require('./middleware/implementation-errors');
const { errors } = require('./auth/authentication-errors');
const { assemble } = require('./composition/participant-authentication.composition');
const { bindings } = require('./bindings/participant-authentication.bindings');

const app = express();
/** @type {(path: string, ...handlers: import('express').RequestHandler[]) => import('express').Express} */
const mount = app.use.bind(app);
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(correlationIdMiddleware);
app.use(wrapJsonParser(express.json({ type: 'application/json', limit: '100kb' }), errors));
app.use(express.static(path.join(__dirname, 'public')));
app.use(publicUiRoutes);
app.use('/api/v1/auth', participantAuthRoutes);
mount('/api/v1', assemble(bindings));
mount('/api/v1', require('./composition/system-administrator-authentication.composition').assemble(bindings));
mount('/api/v1', require('./composition/staff-authentication.composition').assemble(bindings));
mount('/api/v1', require('./composition/system-administrator-bootstrap.composition').assemble(require('./bindings/system-administrator-bootstrap.bindings')));
const administrativeUsers = require('./bindings/administrative-user-creation.bindings');
mount('/api/v1', require('./composition/administrative-user-creation.composition').assemble(administrativeUsers));
app.use(require('./routes/administrative-user-creation.routes').makePageRouter(administrativeUsers));
const catalogue = require('./bindings/program-catalogue.bindings');
mount('/api/v1', require('./composition/program-catalogue.composition').assemble(catalogue));
app.use(require('./routes/program-catalogue-ui.routes').makePageRouter(catalogue));
mount('/api/v1', require('./composition/program-details.composition').assemble(require('./bindings/program-details.bindings')));
app.use(require('./routes/program-details-ui.routes').makePageRouter());
const registrations = require('./bindings/participant-program-registration.bindings');
mount('/api/v1', require('./composition/participant-program-registration.composition').assemble(registrations));
app.use(require('./routes/participant-registration-ui.routes').makePageRouter(registrations, require('./bindings/program-details.bindings').programs));
const cancellation = require('./bindings/participant-registration-cancellation.bindings');
mount('/api/v1', require('./composition/participant-registration-cancellation.composition').assemble(cancellation));
app.use(require('./routes/my-registrations-ui.routes').makePageRouter(cancellation));
const management=require('./bindings/training-program-category-management.bindings');
mount('/api/v1',require('./composition/training-program-category-management.composition').assemble(management));
app.use(require('./routes/training-management-ui.routes').makePageRouter(management));
const registrationManagement = require('./bindings/registration-management-view.bindings');
mount('/api/v1', require('./composition/registration-management-view.composition').assemble(registrationManagement));
app.use(require('./routes/registration-management-ui.routes').makePageRouter(registrationManagement));
const attendance=require('./bindings/attendance-management.bindings');
mount('/api/v1',require('./composition/attendance-management.composition').assemble(attendance));
app.use(require('./routes/attendance-management-ui.routes').makePageRouter(attendance));
const certificates=require('./bindings/certificate-eligibility-issuance.bindings');
mount('/api/v1',require('./composition/certificate-eligibility-issuance.composition').assemble(certificates));
app.use(require('./routes/certificate-management-ui.routes').makePageRouter(certificates));
const reports=require('./bindings/report-generation.bindings');
mount('/api/v1',require('./composition/report-generation.composition').assemble(reports));
app.use(require('./routes/report-generation-ui.routes').makePageRouter(reports));
app.use(errorHandler);
module.exports = app;
